package model.viewObjects;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 09 12:11:42 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MachineMethodsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MachineMethodsVOImpl() {
    }

    /**
     * Returns the variable value for bvMachineName.
     * @return variable value for bvMachineName
     */
    public String getbvMachineName() {
        return (String) ensureVariableManager().getVariableValue("bvMachineName");
    }

    /**
     * Sets <code>value</code> for variable bvMachineName.
     * @param value value to bind as bvMachineName
     */
    public void setbvMachineName(String value) {
        ensureVariableManager().setVariableValue("bvMachineName", value);
    }

    /**
     * Returns the variable value for bvAttributeName.
     * @return variable value for bvAttributeName
     */
    public String getbvAttributeName() {
        return (String) ensureVariableManager().getVariableValue("bvAttributeName");
    }

    /**
     * Sets <code>value</code> for variable bvAttributeName.
     * @param value value to bind as bvAttributeName
     */
    public void setbvAttributeName(String value) {
        ensureVariableManager().setVariableValue("bvAttributeName", value);
    }
}

