package model.applicationModule;


import model.viewObjects.MachineMethodsVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 29 18:25:31 IST 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }


    /**
     * Container's getter for DnsVO1.
     * @return DnsVO1
     */
    public ViewObjectImpl getDnsVO1() {
        return (ViewObjectImpl) findViewObject("DnsVO1");
    }

    /**
     * Container's getter for MachineMethodsVO1.
     * @return MachineMethodsVO1
     */
    public MachineMethodsVOImpl getMachineMethodsVO1() {
        return (MachineMethodsVOImpl) findViewObject("MachineMethodsVO1");
    }

    /**
     * Container's getter for Materialid1.
     * @return Materialid1
     */
    public ViewObjectImpl getMaterialid1() {
        return (ViewObjectImpl) findViewObject("Materialid1");
    }
}

